# Z = 10
# if Z >= 10:
#     print("Z is greater than or equal to 10")

# A = 6
# if A >= 10:
#     print("A is greater than or equaal to 10")
# else:
#     print("A is not greater than or equal to 10")

# B = 16
# if B == 10:
#     print("B is equal to 10")
# elif B >= 10:
#     print("B s greater than or equal to 10")
# else:
#     print("B is not eligible for this condition")

# C = 3
# if C > 5:
#     if C < 10:
#         print("C is between 6 and 9")

# A = 10
# B = 20
# print(A+B)

# a = 20
# b = 10
# print(a-b)

# a = 10
# b = 2
# print(a*b)

# a = 10
# b = 20
# print(a/b)

# a = 30
# b = 10
# print(a%b)

print(eval(input(
     "enter arithmetic exp:")))

